parameters:
  paths:
    - ./src/Inventory
  layers:
    - name: InventoryModule
      collectors:
        - type: bool
          must:
            - type: className
              regex: Laracon\\Inventory\\.*
          must_not:
            - type: className
              regex: Laracon\\Inventory\\Contracts\\.*
    - name: App
      collectors:
        - type: className
          regex: App\\.*
    - name: Contract
      collectors:
        - type: className
          regex: Laracon\\[^\\]*\\Contracts\\.*
    - name: Laravel
      collectors:
        - type: className
          regex: (Laravel|Illuminate)\\.*
  ruleset:
    InventoryModule:
      - App
      - Contract
      - Laravel
